<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ContosoCommerce.Orders</RootNamespace>
    <AssemblyName>ContosoCommerce.Orders</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference
      Include="Microsoft.EntityFrameworkCore"
      Version="8.0.2" />
    <PackageReference
      Include="Microsoft.Extensions.Logging.Abstractions"
      Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference
      Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="..\ContosoCommerce.Core\ContosoCommerce.Core.csproj" />
    <ProjectReference
      Include="..\ContosoCommerce.Data\ContosoCommerce.Data.csproj" />
    <ProjectReference
      Include="..\ContosoCommerce.Users\ContosoCommerce.Users.csproj" />
    <ProjectReference Include=
      "..\ContosoCommerce.Inventory\ContosoCommerce.Inventory.csproj" />
  </ItemGroup>
</Project>
